[package]
name = "ReactDevtoolsCore"
version = { workspace = true }
authors = { workspace = true }
publish = true
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
SafeFlags = { workspace = true }
ReactDevtoolsShared = { path = "../react-devtools-shared" }
ReactGlobals = { path = "../react-globals" }
ReactTelemetry = { path = "../react-telemetry" }

[dev_dependencies]
JestGlobals = { workspace = true }
